### ISSUE TITLE
The code of link prediction on graphs

### ISSUE THREAD

**Issue by liunianxuxie** [nicola-decao/s-vae-pytorch#12]
Hi, thanks for your code. I think your research is significance. I am interseted in the performance of this work in link prediction on graphs. I will appreciate it if you can provide the code of this work.

**Comment by nicola-decao** [comment]
Hi @liunianxuxie, I do not have the code for that particular experiment anymore but it was obtained chaining a few lines from Thomas Kipf's implementation:
* https://github.com/tkipf/gcn for tensorflow
* https://github.com/tkipf/pygcn for pytorch
* https://github.com/tkipf/gae only pytorch

Basically you only need to substitute the Gaussian with our von Mises-Fisher (and allow the dot-product to be larger than `[-1, 1]` multiplying it by a learnable parameter) and you should be done.

I hope it helps.

**Comment by liunianxuxie** [comment]
Sorry, I don’t know what it means (and allow the dot-product to be larger than [-1, 1] multiplying it by a learnable parameter).

**Comment by nicola-decao** [comment]
Here you put our vMF

https://github.com/tkipf/gae/blob/0ebbe9b9a8f496eb12deb9aa6a62e7016b5a5ac3/gae/model.py#L112

https://github.com/tkipf/gae/blob/0ebbe9b9a8f496eb12deb9aa6a62e7016b5a5ac3/gae/optimizer.py#L33

and since the reconstruction is done with dot-product, and our vectors lie in an hypersphere, they are in `[-1,1]` so here

https://github.com/tkipf/gae/blob/0ebbe9b9a8f496eb12deb9aa6a62e7016b5a5ac3/gae/model.py#L114

you can allow them to be `[-k,k]` with a learnable parameter `k`.

**Comment by liunianxuxie** [comment]
I'm really sorry to disturb you again. Can you tell me specifically how to modify it? I just learned deep learning shortly, so I still don’t know how to modify it. Thank you so much.👍
